Create Caroussel
WildCodeSchool/p2-g3-sept21-lille-react-superHeros pull request #1
Opened 2021-10-29 08:32 UTC by Franck59840

Create components Slider  (Slider Data , SliderImage and Slider Css)

2021-10-29 09:03 UTC, Vjerem submitted a review, later dismissed

2021-11-03 10:32 UTC, LoicBrassart requested changes
Some things to fix (or at least explain to me)

2021-11-03 10:32 UTC, LoicBrassart commented on src/components/slider/ImageSlider.jsx
> +    setCurrent(current === length - 1 ? 0 : current + 1);
Use instead: `setCurrent((current+1)%length)`

2021-11-03 10:32 UTC, LoicBrassart commented on src/components/slider/ImageSlider.jsx
> +  const prevSlide = () => {
Same

2021-11-03 10:32 UTC, LoicBrassart commented on src/components/slider/SliderData.jsx
> +  },
I don't get why you use objects to store simple data
Why not something like `[imageOne, imageTwo, imageThree, ...]` ? Do you plan on adding more data to these objects ?

2021-11-03 10:32 UTC, LoicBrassart commented on src/components/slider/ImageSlider.jsx
> +  }
- `slides` should be a string according to your propTypes, why do you test whether it's an array ?
- You could remove the whole condition and do something like:
```
return slides.length &&     <section className="slider">[...]</section
```

2021-11-04 14:50 UTC, KeerhemFR submitted a review, later dismissed
Seems fine to me

2021-11-05 11:21 UTC, KeerhemFR approved these changes
Seems good to me

2021-11-08 08:35 UTC, Hacene010 approved these changes
seems ok

2021-11-09 15:37 UTC, closed without merging