created Rules page
WildCodeSchool/p2-g3-sept21-lille-react-superHeros pull request #15
Opened 2021-11-16 15:36 UTC by IrohsTea

2021-11-16 18:35 UTC, Franck59840 requested changes

2021-11-16 18:35 UTC, Franck59840 commented on src/Components/Rules/index.css
> +    /* width: 100%; */
Why comment ?

2021-11-17 14:59 UTC, Franck59840 submitted a review, later dismissed
good

2021-11-17 15:22 UTC, LoicBrassart approved these changes, later dismissed
Saw no Evil

2021-11-17 15:59 UTC, Vjerem approved these changes
it's great for me

2021-11-18 09:20 UTC, LoicBrassart approved these changes
Saw no Evil

2021-11-18 09:25 UTC, merged