finalized (hopefully) the nabber
WildCodeSchool/p2-g3-sept21-lille-react-superHeros pull request #23
Opened 2021-11-17 17:44 UTC by IrohsTea

made the navbar shrink when clicking on it while it is extended. slowed down the transition. removed the yellow bars button decorations

2021-11-17 18:48 UTC, Franck59840 submitted a review, later dismissed
good

2021-11-18 09:21 UTC, LoicBrassart requested changes, later dismissed
Dead code to remove

2021-11-18 09:21 UTC, LoicBrassart commented on src/Components/Navbar/index.jsx
> +  // const hideSidebar = () => setSidebar(sidebar);
Dead code

2021-11-18 09:42 UTC, LoicBrassart commented
Fix conflicts and reassign

2021-11-18 09:43 UTC, Franck59840 approved these changes, later dismissed
Good delete dead code

2021-11-18 09:44 UTC, LoicBrassart commented
Fix conflicts and reassign

2021-11-18 11:25 UTC, Hacene010 reviewed
No SM validation

2021-11-18 11:47 UTC, IrohsTea commented
but... he commented "good" 😭

2021-11-18 11:51 UTC, Hacene010 commented
> but... he commented "good" sob

Yes but you changed some things after his comment :). So he must validate them again

2021-11-18 12:26 UTC, Franck59840 approved these changes
Good

2021-11-18 12:33 UTC, Hacene010 approved these changes

2021-11-18 15:53 UTC, Franck59840 approved these changes

2021-11-18 17:21 UTC, merged