Home blog
WildCodeSchool/p2-g3-sept21-lille-react-superHeros pull request #3
Opened 2021-11-03 15:09 UTC by Vjerem

Update HomeBlog

2021-11-03 15:31 UTC, KeerhemFR requested changes
Your part seems okay to me, but you worked on files which you shouldn't have, so I can't accept the PR
I left comments where it isn't good, please change that and the review will be okay for me.

2021-11-03 15:31 UTC, KeerhemFR commented on public/index.html
> +  <body style="background-color: #2d4059">
Has nothing to do with the HomeBlog, and changing an element style in the html elements besides by changing it in a css file is a bad practice

2021-11-03 15:31 UTC, KeerhemFR commented on src/App.css
> +}
?

2021-11-03 15:31 UTC, KeerhemFR commented on src/App.jsx
> +  );
Everything related to the HomeBlog should be load in the homepage.jsx beside the app.jsx

2021-11-03 16:17 UTC, KeerhemFR approved these changes, later dismissed
Allright, previous mistakes were corrected, everything is fine for me.

2021-11-04 09:27 UTC, Hacene010 requested changes
Some syntax errors to fix

2021-11-04 09:27 UTC, Hacene010 commented on src/Components/HomeBlog/Index.css
> +.HomeNews {
use camelCase instead of PascalCase for the className.

2021-11-04 09:27 UTC, Hacene010 commented on src/Components/HomeBlog/Index.css
> +  .HomeNews {
Same here

2021-11-04 09:27 UTC, Hacene010 commented on src/Components/HomeBlog/index.jsx
> +    <section className="HomeNews">
Same here (camelCase)

2021-11-04 10:50 UTC, Hacene010 approved these changes
Ok but you need to fix the problem with your App.jsx

2021-11-04 10:54 UTC, KeerhemFR approved these changes
Everything seems fine to me

2021-11-04 10:55 UTC, merged