1. Created the sidebar with logos in it. 2. Also created the links to…
WildCodeSchool/p2-g3-sept21-lille-react-superHeros pull request #6
Opened 2021-11-04 16:19 UTC by IrohsTea

…wards other pages

2021-11-04 16:31 UTC, KeerhemFR approved these changes, later dismissed
Everything seems okay

2021-11-04 17:01 UTC, Hacene010 requested changes
Still some evils to fix.

2021-11-04 17:01 UTC, Hacene010 commented on src/Components/Navbar/Index.jsx
> +          <img src={NavbarLogo} alt="" />
Put something into the alt plz!!!

2021-11-04 17:01 UTC, Hacene010 commented on src/Components/Navbar/Index.jsx
> +          <img src={WildHeroesBurger} alt="" />
Same here !

2021-11-05 14:28 UTC, KeerhemFR submitted a review, later dismissed
Seems okay to me

2021-11-08 08:45 UTC, Hacene010 approved these changes, later dismissed
Ok but check the comment plz

2021-11-08 08:45 UTC, Hacene010 commented on src/App.jsx
> +        <Route path="/" exact component={Home} />
Does it work like that (with the "exact" after the path )? because I know that we write it like this ( " exact path=' /' )

2021-11-08 13:27 UTC, KeerhemFR approved these changes
It's okay for me.

2021-11-08 15:02 UTC, Hacene010 approved these changes
ok

2021-11-09 15:13 UTC, merged